# Women Cloth Reviews Prediction with Multinomial Naive Bayes
# YBIF Handson Project-05
# Yada Roshik

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('Womens Clothing E-Commerce Reviews.csv')

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [4]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [5]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Clothing ID              23486 non-null  int64 
 1   Age                      23486 non-null  int64 
 2   Title                    19676 non-null  object
 3   Review Text              22641 non-null  object
 4   Rating                   23486 non-null  int64 
 5   Recommended IND          23486 non-null  int64 
 6   Positive Feedback Count  23486 non-null  int64 
 7   Division Name            23472 non-null  object
 8   Department Name          23472 non-null  object
 9   Class Name               23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [7]:
df.shape

(23486, 10)

## Missing values
### Remove missing values in Rview columns with no review text

In [8]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
df[df['Review Text']== ""]=np.NaN

In [10]:
df['Review Text'].fillna('No Review',inplace=True)

In [11]:
df.isna().sum()

Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [12]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

## Define Target (y) and Feature (X)

In [13]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [14]:
X=df['Review Text']

In [15]:
y=df['Rating']

In [16]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=182529)

In [19]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Get Feature Text Conversion to Tokens

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [22]:
X_train=cv.fit_transform(X_train)

In [23]:
cv.get_feature_names_out()

array(['00p 0p', '0p fit', '10 12', ..., 'yellow color', 'yes runs',
       'yoga pants'], dtype=object)

In [24]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
X_test = cv.fit_transform(X_test)

In [26]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 dress', ..., 'years come', 'yoga pants',
       'zipper bit'], dtype=object)

In [27]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Get Model Train

In [28]:
from sklearn.naive_bayes import MultinomialNB

In [29]:
model=MultinomialNB()

In [30]:
model.fit(X_train,y_train)

MultinomialNB()

## Get Model Prediction

In [31]:
y_pred=model.predict(X_test)

In [32]:
y_pred.shape

(7046,)

In [33]:
y_pred

array([5., 4., 3., ..., 1., 5., 3.])

## Get Probability of Each Predicted Class

In [34]:
model.predict_proba(X_test)

array([[0.16893479, 0.08936107, 0.06486659, 0.03024582, 0.64659173],
       [0.03834369, 0.00450724, 0.0138028 , 0.74335022, 0.19999605],
       [0.02901835, 0.35588795, 0.45210009, 0.08918447, 0.07380913],
       ...,
       [0.44638504, 0.00123337, 0.00683598, 0.26851991, 0.2770257 ],
       [0.02304922, 0.07117497, 0.0373725 , 0.19240357, 0.67599975],
       [0.10401402, 0.24089302, 0.49751917, 0.13372724, 0.02384654]])

## Get Model Evaluation

In [35]:
from sklearn.metrics import confusion_matrix, classification_report

In [36]:
print(confusion_matrix(y_test, y_pred))

[[  21   19   30   50  129]
 [  68   46   61   78  230]
 [ 106  102  117  133  404]
 [ 199  144  179  276  772]
 [ 450  300  417  665 2050]]


In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.08      0.04       249
         2.0       0.08      0.10      0.08       483
         3.0       0.15      0.14      0.14       862
         4.0       0.23      0.18      0.20      1570
         5.0       0.57      0.53      0.55      3882

    accuracy                           0.36      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.36      0.37      7046



## Recategories Rating as Poor (0) and Good (1)

In [38]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [39]:
df.replace({'Rating' : {1:0, 2:0, 3:0, 4:1, 5:1}}, inplace=True)

In [40]:
y=df['Rating']

In [41]:
X=df['Review Text']

## Train Test Split

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,stratify=y,random_state=182529)

In [44]:
X_train.shape,X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Get Feature Text Conversion to Tokens

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [47]:
X_train=cv.fit_transform(X_train)

In [48]:
X_test=cv.fit_transform(X_test)

## Get Model Re-Train

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
model=MultinomialNB()

In [51]:
model.fit(X_train,y_train)

MultinomialNB()

## Get Model Prediction

In [52]:
y_pred=model.predict(X_test)

In [53]:
y_pred.shape

(7046,)

In [54]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

## Get Model Evaluation

In [55]:
from sklearn.metrics import confusion_matrix,classification_report

In [56]:
print(confusion_matrix(y_test,y_pred))

[[ 517 1066]
 [ 877 4586]]


In [57]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.37      0.33      0.35      1583
         1.0       0.81      0.84      0.83      5463

    accuracy                           0.72      7046
   macro avg       0.59      0.58      0.59      7046
weighted avg       0.71      0.72      0.72      7046

